@startuml Factory Method

interface Factory<<interface>>{
    + {static} FactoryMethod() : Product
}

class ConcreteFactory{
    + {static} FactoryMethod() :  Product 
    
}
note left 
    implements 
    <b>Factory Method</b>
end note

interface Product<<interface>>

class ConcreteProductA
class ConcreteProductB

class Client


ConcreteFactory --|> Factory






@enduml